### PR TITLE
Allow additional options for request

### PR DESCRIPTION
**Pull request by Zefau**
This pr allows additional options for request.
I'm using it to use self-signed certificates when `https` is enabled.

### CODE REVIEW

**Comment by Zefau** [comment]
@phillipj

**Comment by phillipj** [comment]
Cool, I'm all for merging things that has proven valuable to using projects
👌

Only thought that struck my mind when seeing this, is whethe or not we
should do the spread of additional options last than the first? Rationale
being that one might get the chance to override a value this package sets
by default.. Any thoughts on that?

**Comment by Zefau** [comment]
Not sure if I understood you right. The params given by `this.requestOptions` will always be overwritten in case `reqOpts` defines an alternative. Is that what you mean?

See this fiddle: https://jsfiddle.net/40q7eykz/

```js
let additionalParams = {
  uri: "this will be overwritten",
  method: 'this will be overwritten',
  ca_cert: "this will be added",
  great: "this will be added"
}

let reqOpts = {
  ...additionalParams,
  uri: "this will be used",
  encoding: "this will be used",
  method: "this will be used"
};

console.log(reqOpts);
```

**Excepted output:**
Params `uri` and `method` of `additionalParams` will be overwritten by `reqOpts`.
```js
[object Object] {
  ca_cert: "this will be added",
  encoding: "this will be used",
  great: "this will be added",
  method: "this will be used",
  uri: "this will be used"
}
```

**Comment by phillipj** [comment]
Nice writeup, concrete examples makes it a lot easier for us to not talk past each other 💯 

What I tried to ask was to allow those additional parameters to overwrite what's usually set by this code:

https://github.com/phillipj/node-plex-api/blob/98c81ee8f9756b41516b2443c046b3e9d1ff554c/lib/api.js#L169-L176

Guess one could say doing the opposite of what you have in your **expected output**.

Why? Because otherwise, some of those options can't be overwritten and in certain scenarios that I can't foresee, that might be really valuable. So to avoid having to open an issue / PR to make it configurable, why not use this PR to open up for that right away while we're at it? 🤷‍♂

**Comment by Zefau** [comment]
Thanks for the feedback. I initially thought its better to keep what's set by the API, but since this is an advanced option, I agree with you and we should give full flexibility. 

I changed it now to
```js
    var reqOpts = {
        uri: url.parse(reqUrl),
        encoding: null,
        method: method || 'GET',
        timeout: timeout,
        gzip: true,
        headers: requestHeaders,
        ...this.requestOptions
    };
```

**Comment by phillipj** [comment]
Awesome, good to hear it made sense to anyone else as well.

Took the liberty of pushing an update to `Readme.me` directly to you branch to update the meaning of the new option we're adding here.

Thanks a bunch for sharing valuable additions to the package 👍

**Comment by phillipj** [comment]
v5.3.0 just got published with this addition included 🚀

**Pull request merged**
