### PR TITLE
Satisfy npm audit

### PR DESCRIPTION
**Pull request by au5ton**
For the first commit, I ran `npm audit fix`. However, one devDependency could not be automatically resolved, so I manually updated it to the version with vulnerability patch in the next commit.

When I ran `npm test` on my local machine, this only failed the timeout test.

### CODE REVIEW

**Comment by au5ton** [comment]
@phillipj

**Comment by phillipj** [comment]
Great @au5ton, thanks a lot!

> When I ran `npm test` on my local machine, this only failed the timeout test.

Just to clarify, does it fail on your local machine now? Or was that before you updated mocha?

**Comment by au5ton** [comment]
On both mocha 2.5.1 and (proposed) mocha 4.0.1 I get the same error:

```
  1) timeout error
       returns error on timeout:
     Error: expected undefined to equal 'ESOCKETTIMEDOUT'
      at Assertion.assert (node_modules/expect.js/index.js:96:13)
      at Assertion.be.Assertion.equal (node_modules/expect.js/index.js:216:10)
      at Assertion.(anonymous function) [as be] (node_modules/expect.js/index.js:69:24)
      at test/timeout-test.js:26:37
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by phillipj** [comment]
Thanks for the quick response! Strange, cause it works on my machine ™️.

I'll try to get Travis CI up-n-running in the repo again, making that the source of truth for matters like this.

**Comment by phillipj** [comment]
Got successful builds on Travis CI: https://travis-ci.org/phillipj/node-plex-api/builds/416241454

Therefore merging this as is, thanks a lot! 👍 

*Please share more details about your setup, especially Node.js & npm versions, to see if we can reproduce the errors you're seeing.*

**Comment by phillipj** [comment]
FYI I found a way to reproduce you're issues by running more versions on Travis: https://github.com/phillipj/node-plex-api/pull/96

**Comment by au5ton** [comment]
friendly reminder to please push this to npm at your convenience

**Comment by phillipj** [comment]
Thanks Austin! I want to have a quick look at what's causing some async
trouble with Node.js 10 before publishing a new version, especially to
check if it's introduced by these changes.

**Comment by phillipj** [comment]
@au5ton v5.2.1 has been published, thanks again!

Long story short, I re-created `package-lock.json` to get tests to pass on Node.js 10.

**Pull request merged**
