### PR TITLE
Send X-Plex headers on every request, update defaults, add missing headers

### PR DESCRIPTION
**Pull request by OverloadUT**
* The X-Plex headers are now sent on every request. This appears to be necessary in certain requests, such as playMedia. It's probably best for forwards-compatibility to simply send them all with every request.
* Added some missing X-Plex headers: deviceName, platformVersion
* Updated the default X-Plex headers to be a bit more descriptive, and more closely match what they are used for in official Plex apps
* Updated the readme to explain each of the X-Plex headers
* Added an image for the readme that illustrates how the X-Plex headers are displayed on the Plex website.

### CODE REVIEW

**Comment by phillipj** [comment]
Really appreciate what you have done here, especially better documentation :+1:

**Comment by onedr0p** [comment]
Looks great guys!

**Comment by phillipj** [comment]
Hey thanks there @onedr0p! @OverloadUT is really pushing this project to a better place these days :smile: Very excited we just got v3.0.0 out :dancer:

**Comment by OverloadUT** [comment]
And with 3.0.0, I can update my project to point at the official npm package again!

**Comment by onedr0p** [comment]
I would love to see what projects evolve with using this module. I was attempting to work on a front end to Plex to show library stats, user watch stats etc.. using node and express; however, work is getting in the way of making any real progress. Who wants to develop in their free time when they work as a developer 9 hours a day. ^_^

**Comment by phillipj** [comment]
> Who wants to develop in their free time when they work as a developer 9 hours a day

I do! :smiley_cat: Couldnt agree with you more about seeing what people are actually creating with this module. A list of example apps out there would have been great.

**Pull request merged**
