### PR TITLE
Fix filterChildrenByCriterias from pms v1.3

### PR DESCRIPTION
**Pull request by Andy1210**

### CODE REVIEW

**Comment by phillipj** [comment]
Hi @Andy1210,

thanks so much for your contribution 👍 

Do you have an example response from PMS v1.3 by any chance? That would make it a lot easier for us to make a test to verify that this added functionality works in the future.

**Comment by Andy1210** [comment]
```
{
    MediaContainer: {
        size: 3,
        Server: [{
                name: 'RasPlex',
                host: '192.168.1.29',
                address: '192.168.1.29',
                port: 3005,
                machineIdentifier: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
                version: '1.8.0.148-573b6d73',
                protocol: 'plex',
                product: 'plexhometheater',
                deviceClass: 'pc',
                protocolVersion: '1',
                protocolCapabilities: 'navigation,playback,timeline,mirror,playqueues'
            },
            {
                name: 'RasPlex',
                host: '192.168.1.48',
                address: '192.168.1.48',
                port: 3005,
                machineIdentifier: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
                version: '1.8.0.148-573b6d73',
                protocol: 'plex',
                product: 'plexhometheater',
                deviceClass: 'pc',
                protocolVersion: '1',
                protocolCapabilities: 'navigation,playback,timeline,mirror,playqueues'
            },
            {
                name: 'RasPlex',
                host: '192.168.1.5',
                address: '192.168.1.5',
                port: 3005,
                machineIdentifier: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
                version: '1.8.0.148-573b6d73',
                protocol: 'plex',
                product: 'plexhometheater',
                deviceClass: 'pc',
                protocolVersion: '1',
                protocolCapabilities: 'navigation,playback,timeline,mirror,playqueues'
            }
        ]
    }
}
```

Unfortunately my fix wont work for the "currently.paused" and "currently.playing" functions. That part should also be modified, because the /status/sessions response also different.

```
{
    MediaContainer: {
        size: 1,
        Video: [{
            addedAt: '1445361749',
            art: '/library/metadata/4528/art/1445361852',
            audienceRatingImage: 'rottentomatoes://image.rating.spilled',
            chapterSource: 'agent',
            contentRating: 'PG',
            duration: '7803680',
            guid: 'com.plexapp.agents.imdb://tt1964418?lang=hu',
            key: '/library/metadata/4528',
            lastViewedAt: '1511721539',
            librarySectionID: '1',
            librarySectionKey: '/library/sections/1',
            originalTitle: 'Tomorrowland',
            originallyAvailableAt: '2015-05-22',
            primaryExtraKey: '/library/metadata/4529',
            rating: '6.3',
            ratingImage: 'rottentomatoes://image.rating.rotten',
            ratingKey: '4528',
            sessionKey: '94',
            studio: 'Walt Disney Pictures',
            summary: 'Frank, az egykori gyerekzseni és Casey, a mindig optimista, tudományos érdeklődésű tinédzser közös álmot kergetnek. Hogy végzetüket beteljesítsék, egy veszélyekkel teli küldetésbe kezdenek, amelynek keretében szeretnék megtalálni a térben és időben meghatározhatatlan helyen fekvő titokzatos helyet, amelyet Tomorrowland néven ismernek. Tettük azonban nem csak rájuk, hanem az egész világra hatással van, amely így akár örökre megváltozhat.',
            thumb: '/library/metadata/4528/thumb/1445361852',
            title: 'Holnapolisz',
            type: 'movie',
            updatedAt: '1445361852',
            viewCount: '6',
            viewOffset: '3198353',
            year: '2015',
            Media: [{
                aspectRatio: '2.20',
                audioChannels: '6',
                audioCodec: 'ac3',
                bitrate: '1723',
                container: 'mkv',
                duration: '7803680',
                height: '328',
                id: '8007',
                videoCodec: 'h264',
                videoFrameRate: '24p',
                videoProfile: 'high',
                videoResolution: 'sd',
                width: '720',
                selected: true,
                Part: [{
                    container: 'mkv',
                    duration: '7803680',
                    file: '/home/andy1210/Media2/Movies/Tomorrowland.2015.BDRip.x264.HuN-HRT/hrt-tomorrowland.2015.bdrip.x264.mkv',
                    id: '8051',
                    indexes: 'sd',
                    key: '/library/parts/8051/1445361743/file.mkv',
                    size: '1680888455',
                    videoProfile: 'high',
                    decision: 'directplay',
                    selected: true,
                    Stream: [{
                            bitDepth: '8',
                            bitrate: '1305',
                            cabac: '1',
                            chromaSubsampling: '4:2:0',
                            codec: 'h264',
                            codecID: 'V_MPEG4/ISO/AVC',
                            colorRange: 'tv',
                            colorSpace: 'bt709',
                            default: '1',
                            duration: '7803679',
                            frameRate: '23.976',
                            frameRateMode: 'cfr',
                            hasScalingMatrix: '0',
                            height: '328',
                            id: '77543',
                            index: '0',
                            language: 'English',
                            languageCode: 'eng',
                            level: '41',
                            pixelFormat: 'yuv420p',
                            profile: 'high',
                            refFrames: '16',
                            scanType: 'progressive',
                            streamType: '1',
                            title: 'x264 @ HRT',
                            width: '720',
                            location: 'direct'
                        },
                        {
                            audioChannelLayout: '5.1(side)',
                            bitDepth: '16',
                            bitrate: '384',
                            bitrateMode: 'cbr',
                            channels: '6',
                            codec: 'ac3',
                            codecID: 'A_AC3',
                            default: '1',
                            dialogNorm: '-27',
                            duration: '7803680',
                            id: '77544',
                            index: '1',
                            language: 'Magyar',
                            languageCode: 'hun',
                            samplingRate: '48000',
                            selected: '1',
                            streamType: '2',
                            title: 'Hungarian DD5.1 @ 384 kbps',
                            location: 'direct'
                        },
                        {
                            codec: 'srt',
                            codecID: 'S_TEXT/UTF8',
                            default: '1',
                            forced: '1',
                            format: 'srt',
                            id: '77545',
                            index: '2',
                            language: 'Magyar',
                            languageCode: 'hun',
                            selected: '1',
                            streamType: '3',
                            title: 'Forced',
                            location: 'sidecar-subs'
                        }
                    ]
                }]
            }],
            Genre: [{
                    count: '145',
                    filter: 'genre=129',
                    id: '129',
                    tag: 'Fantasy'
                },
                {
                    count: '230',
                    filter: 'genre=163',
                    id: '163',
                    tag: 'Akció'
                },
                {
                    count: '233',
                    filter: 'genre=128',
                    id: '128',
                    tag: 'Kaland'
                },
                {
                    count: '132',
                    filter: 'genre=29',
                    id: '29',
                    tag: 'Sci-Fi'
                },
                {
                    count: '35',
                    filter: 'genre=1303',
                    id: '1303',
                    tag: 'Rejtély'
                }
            ],
            Director: [{
                count: '3',
                filter: 'director=9134',
                id: '9134',
                tag: 'Brad Bird'
            }],
            Writer: [{
                    count: '3',
                    filter: 'writer=9135',
                    id: '9135',
                    tag: 'Brad Bird'
                },
                {
                    filter: 'writer=9136',
                    id: '9136',
                    tag: 'Damon Lindelof'
                }
            ],
            Producer: [{
                    filter: 'producer=9180',
                    id: '9180',
                    tag: 'Damon Lindelof'
                },
                {
                    filter: 'producer=9181',
                    id: '9181',
                    tag: 'Brad Bird'
                },
                {
                    filter: 'producer=9182',
                    id: '9182',
                    tag: 'Jeffrey Chernov'
                }
            ],
            Country: [{
                count: '707',
                filter: 'country=33',
                id: '33',
                tag: 'USA'
            }],
            Role: [{
                    count: '5',
                    filter: 'actor=1190',
                    id: '1190',
                    role: 'Casey Newton',
                    tag: 'Britt Robertson',
                    thumb: 'http://image.tmdb.org/t/p/original/32ovcCVfAUYrJof6IDaoS1FPJG3.jpg'
                },
                {
                    count: '4',
                    filter: 'actor=5700',
                    id: '5700',
                    role: 'Frank Walker',
                    tag: 'George Clooney',
                    thumb: 'http://image.tmdb.org/t/p/original/z4SBfpKDThuQY0FsvDbajcooBdA.jpg'
                },
                {
                    count: '3',
                    filter: 'actor=9137',
                    id: '9137',
                    role: 'Athena',
                    tag: 'Raffey Cassidy',
                    thumb: 'http://image.tmdb.org/t/p/original/2k7gMSOAoUS1I90bTRZa89IlBem.jpg'
                },
                {
                    filter: 'actor=9138',
                    id: '9138',
                    role: 'Young Frank Walker',
                    tag: 'Thomas Robinson',
                    thumb: 'http://image.tmdb.org/t/p/original/duhdLnjGG7s05T4xjXDu7ISYKeN.jpg'
                },
                {
                    count: '4',
                    filter: 'actor=5722',
                    id: '5722',
                    role: 'David Nix',
                    tag: 'Hugh Laurie',
                    thumb: 'http://image.tmdb.org/t/p/original/3qCmEHtq5fBW8dbzsYDSy16Zqb0.jpg'
                },
                {
                    count: '4',
                    filter: 'actor=2713',
                    id: '2713',
                    role: 'Ursula',
                    tag: 'Kathryn Hahn',
                    thumb: 'http://image.tmdb.org/t/p/original/nud8mW28WZMHKYmxkjDCumbGpTJ.jpg'
                },
                {
                    count: '8',
                    filter: 'actor=6196',
                    id: '6196',
                    role: 'Hugo',
                    tag: 'Keegan-Michael Key',
                    thumb: 'http://image.tmdb.org/t/p/original/gqPRozx8ppAg2TSjW3ww56LnIZr.jpg'
                },
                {
                    filter: 'actor=9139',
                    id: '9139',
                    role: 'Eddie Newton',
                    tag: 'Tim McGraw',
                    thumb: 'http://image.tmdb.org/t/p/original/lotQwKKAUe3hI4EnmMySNpJGKGO.jpg'
                },
                {
                    count: '2',
                    filter: 'actor=9140',
                    id: '9140',
                    role: 'Frank\'s Dad',
                    tag: 'Chris Bauer',
                    thumb: 'http://image.tmdb.org/t/p/original/3KYVMaGkWTEDQ0T9lsu85pVbP4T.jpg'
                },
                {
                    count: '2',
                    filter: 'actor=9141',
                    id: '9141',
                    role: 'Nate Newton',
                    tag: 'Pierce Gagnon',
                    thumb: 'http://image.tmdb.org/t/p/original/qCTyJl6aBUupo3FsmP9e5SEYxMS.jpg'
                },
                {
                    filter: 'actor=9142',
                    id: '9142',
                    role: 'Dave Clark',
                    tag: 'Matthew MacCaull',
                    thumb: 'http://image.tmdb.org/t/p/original/aRIdwgwZ6pXK8W6gXR8ZftGxXHp.jpg'
                },
                {
                    count: '4',
                    filter: 'actor=9037',
                    id: '9037',
                    role: 'Jenny Newton',
                    tag: 'Judy Greer',
                    thumb: 'https://thetvdb.com/banners/actors/135761.jpg'
                },
                {
                    filter: 'actor=9143',
                    id: '9143',
                    role: 'Bus Driver',
                    tag: 'Matthew Kevin Anderson',
                    thumb: 'http://image.tmdb.org/t/p/original/vH00XgFKbg1jWCgGRmMoQ8SCSv3.jpg'
                },
                {
                    filter: 'actor=9144',
                    id: '9144',
                    role: 'Small World Operator',
                    tag: 'Michael Giacchino',
                    thumb: 'http://image.tmdb.org/t/p/original/2YW8sSVvRhCwiQmsFCgtFsGkbv8.jpg'
                },
                {
                    filter: 'actor=9145',
                    id: '9145',
                    role: 'Skyscraper Foreman',
                    tag: 'D. Harlan Cutshall',
                    thumb: 'http://image.tmdb.org/t/p/original/p875VwQPNRRMFzPWkFBSWOG4TrI.jpg'
                },
                {
                    filter: 'actor=9146',
                    id: '9146',
                    role: 'Young Casey Newton',
                    tag: 'Shiloh Nelson',
                    thumb: 'http://image.tmdb.org/t/p/original/3PLDxnmtSYTmcHXwxXIXfHLs0T4.jpg'
                },
                {
                    filter: 'actor=9147',
                    id: '9147',
                    role: 'History Teacher',
                    tag: 'Xantha Radley',
                    thumb: 'http://image.tmdb.org/t/p/original/lK9R1HcaFAjprgGI48X32oCdgE4.jpg'
                },
                {
                    filter: 'actor=9148',
                    id: '9148',
                    role: 'Science Teacher',
                    tag: 'David Nykl',
                    thumb: 'http://image.tmdb.org/t/p/original/u3HwiO27T6E4V8M73MaqwZbV5Pm.jpg'
                },
                {
                    count: '2',
                    filter: 'actor=9149',
                    id: '9149',
                    role: 'English Teacher',
                    tag: 'Paul McGillion',
                    thumb: 'http://image.tmdb.org/t/p/original/n6S66CIpNqThe6eugr94WZBbI6u.jpg'
                },
                {
                    filter: 'actor=9150',
                    id: '9150',
                    role: 'Beefy Cop',
                    tag: 'Pearce Visser',
                    thumb: 'http://image.tmdb.org/t/p/original/4achg9CPtd42YiTWULQcvHvOMFj.jpg'
                },
                {
                    count: '2',
                    filter: 'actor=9151',
                    id: '9151',
                    role: 'Jail Desk Jockey',
                    tag: 'Garry Chalk',
                    thumb: 'http://image.tmdb.org/t/p/original/1estlif6pDM9uV7sgOsTU3WQeYw.jpg'
                },
                {
                    filter: 'actor=9152',
                    id: '9152',
                    role: 'Jail Punk',
                    tag: 'Dagan Nish'
                },
                {
                    filter: 'actor=9153',
                    id: '9153',
                    role: 'Jetpack Dexter',
                    tag: 'Yusuf A. Ahmed'
                },
                {
                    filter: 'actor=9154',
                    id: '9154',
                    role: 'Jetpack Buddy',
                    tag: 'Alex Barima'
                },
                {
                    filter: 'actor=9155',
                    id: '9155',
                    role: 'Jetpack Buddy',
                    tag: 'Jedidiah Goodacre',
                    thumb: 'http://image.tmdb.org/t/p/original/7EXz5Y7qRaqQHpYpVumRtmAlz1D.jpg'
                },
                {
                    filter: 'actor=9156',
                    id: '9156',
                    role: 'Monorail Mother',
                    tag: 'Kate Crutchlow'
                },
                {
                    filter: 'actor=9157',
                    id: '9157',
                    role: 'Young Astronaut',
                    tag: 'Priya Rajaratnam'
                },
                {
                    filter: 'actor=9158',
                    id: '9158',
                    role: 'Astronaut\'s Father',
                    tag: 'Parm Soor'
                },
                {
                    filter: 'actor=9159',
                    id: '9159',
                    role: 'Astronaut\'s Mother',
                    tag: 'Leena Manro'
                },
                {
                    filter: 'actor=9160',
                    id: '9160',
                    role: 'Pickup Driver',
                    tag: 'Rick Pearce'
                },
                {
                    filter: 'actor=9161',
                    id: '9161',
                    role: 'Police Captain',
                    tag: 'Tom Butler',
                    thumb: 'http://image.tmdb.org/t/p/original/25mdyFUsVexK1eTHBvlfd8GPmF0.jpg'
                },
                {
                    filter: 'actor=9162',
                    id: '9162',
                    role: 'Deputy',
                    tag: 'Michael Rowe'
                },
                {
                    filter: 'actor=9163',
                    id: '9163',
                    role: 'Deputy (as Tim Perez)',
                    tag: 'Timothy Paul Perez'
                },
                {
                    count: '6',
                    filter: 'actor=1332',
                    id: '1332',
                    role: 'Eiffel Tower Guard #1',
                    tag: 'Patrick Sabongui',
                    thumb: 'http://image.tmdb.org/t/p/original/aEJ7963PHcFLBrXE0qJdS5GfU2L.jpg'
                },
                {
                    filter: 'actor=9164',
                    id: '9164',
                    role: 'Eiffel Tower Guard #2',
                    tag: 'Romuald Hivert'
                },
                {
                    filter: 'actor=9165',
                    id: '9165',
                    role: 'Pierre Clark',
                    tag: 'Mathieu Lardier'
                },
                {
                    filter: 'actor=9166',
                    id: '9166',
                    role: 'Jensen',
                    tag: 'Fraser Corbett'
                },
                {
                    filter: 'actor=9167',
                    id: '9167',
                    role: 'Tough Guard',
                    tag: 'Darren Shahlavi',
                    thumb: 'http://image.tmdb.org/t/p/original/qnije3wcudlIbSjRrNr9A57tjO3.jpg'
                },
                {
                    filter: 'actor=9168',
                    id: '9168',
                    role: 'Young British Recruiter',
                    tag: 'Aidan Gemme'
                },
                {
                    filter: 'actor=9169',
                    id: '9169',
                    role: 'Guitar Player',
                    tag: 'Takayuki Oki'
                },
                {
                    filter: 'actor=9170',
                    id: '9170',
                    role: 'GM Plant Worker',
                    tag: 'Natasha Davidson'
                },
                {
                    filter: 'actor=9171',
                    id: '9171',
                    role: 'Haitian Woman',
                    tag: 'Liliane Leilan Juma'
                },
                {
                    filter: 'actor=9172',
                    id: '9172',
                    role: 'Thick Glasses (uncredited)',
                    tag: 'Paul Anthony',
                    thumb: 'http://image.tmdb.org/t/p/original/mqqoiJjStvalu6QLLRHhbq1NmRQ.jpg'
                },
                {
                    filter: 'actor=9173',
                    id: '9173',
                    role: 'DQ Patron (uncredited)',
                    tag: 'Kenia Arias'
                },
                {
                    filter: 'actor=9174',
                    id: '9174',
                    role: 'Hero Bus Patron (uncredited)',
                    tag: 'Kimberly Arklie'
                },
                {
                    count: '2',
                    filter: 'actor=9175',
                    id: '9175',
                    role: 'World\'s Fair Patron (uncredited)',
                    tag: 'Nicholas Barrera'
                },
                {
                    filter: 'actor=9176',
                    id: '9176',
                    role: 'Dave Clark #7 (uncredited)',
                    tag: 'Jason Bell'
                },
                {
                    filter: 'actor=9177',
                    id: '9177',
                    role: 'Guest (uncredited)',
                    tag: 'Wendy Bell'
                },
                {
                    filter: 'actor=9178',
                    id: '9178',
                    role: 'Pedestrian (uncredited)',
                    tag: 'Aimee Bowen'
                },
                {
                    count: '2',
                    filter: 'actor=9179',
                    id: '9179',
                    role: 'Gentleman - 1964 World Fair (uncredited)',
                    tag: 'Bradley Bowen',
                    thumb: 'http://image.tmdb.org/t/p/original/d8WirJ44GEhK1xe0yNkDHRewoFo.jpg'
                }
            ],
            User: {
                id: '1',
                thumb: 'https://plex.tv/users/xxxxxxxxxxxxxxxx/avatar?c=1511719247',
                title: 'Andy1210'
            },
            Player: {
                address: '192.168.1.48',
                device: 'RaspberryPi',
                machineIdentifier: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
                model: 'RaspberryPi',
                platform: 'Plex Home Theater',
                platformVersion: '',
                product: 'Plex Home Theater',
                profile: 'Raspberry PI',
                remotePublicAddress: 'xx.xx.xx.xx',
                state: 'playing',
                title: 'RasPlex',
                vendor: '',
                version: '1.8.0.148-573b6d73',
                local: true,
                userID: 1
            },
            Session: {
                id: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
                bandwidth: 3171,
                location: 'lan'
            }
        }]
    }
}
```

**Comment by phillipj** [comment]
I'm very sorry and ashamed it took me ~2 years accepting this PR @Andy1210!

This looks like a great start handling PMS v1.3 responses. I took the liberty of pushing a unit test that verifies the expected behaviour to your branch.

As you mention yourself, this doesn't fix all issues related to the PMS v1.3 format, but certainly better than not having your fix in at all. Further improvements can be merged later in separate PRs.

Thanks again!

**Comment by phillipj** [comment]
Pushed this fix to npm as v5.2.3 🚀

**Pull request merged**
